/**
 * State Reconciler — startup intent reconciliation after worker restart (#141)
 *
 * When the bot worker process restarts and a run transitions to RUNNING,
 * there may be stale or orphaned intents from before the crash:
 *
 *   - PENDING intents: generated by a signal that was valid before crash,
 *     but may now be stale (wrong price, wrong market state). These should
 *     be cancelled before the signal engine generates fresh signals.
 *
 *   - PLACED intents: sent to exchange before crash. The existing
 *     reconcilePlacedIntents() poll loop will handle these once the run
 *     is RUNNING. Startup just audits them.
 *
 *   - Position-intent consistency: if an open position exists but there
 *     are stale ENTRY intents, they could cause duplicate entries.
 *
 * This module provides:
 *   - Pure decision functions to classify intent state on startup
 *   - A reconciliation result that the caller uses to act (cancel, audit, log)
 *   - No DB mutations — the caller reads state and applies the decisions
 *
 * Design:
 *   - Pure functions: given intent/position state, return decisions
 *   - Deterministic: same inputs always produce same output
 *   - Idempotent: running reconciliation twice is safe
 *   - Conservative: when in doubt, cancel stale intents rather than act on them
 *
 * Stage 8, issue #141 — slice 2: startup reconciliation
 */

import type { PositionSnapshot } from "./positionManager.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal intent shape needed for startup reconciliation decisions. */
export interface StartupIntent {
  id: string;
  intentId: string;
  state: string;
  type: string;
  side: string;
  orderId: string | null;
  createdAt: Date;
}

/** Result of classifying a single intent on startup. */
export interface IntentClassification {
  intentId: string;
  id: string;
  action: "cancel" | "monitor" | "ok";
  reason: string;
}

/** Full startup reconciliation result for a single run. */
export interface StartupReconciliationResult {
  /** Intents that should be cancelled (stale PENDING). */
  toCancel: IntentClassification[];
  /** Intents that need monitoring (PLACED/PARTIALLY_FILLED without completion). */
  toMonitor: IntentClassification[];
  /** Intents that are already terminal (no action needed). */
  terminal: IntentClassification[];
  /** Whether it's safe to proceed with normal signal evaluation. */
  safeToEvaluate: boolean;
  /** Human-readable summary for logging. */
  summary: string;
  /** Counts by category for structured logging. */
  counts: {
    pending: number;
    placed: number;
    partiallyFilled: number;
    terminal: number;
    total: number;
  };
}

// ---------------------------------------------------------------------------
// Intent classification
// ---------------------------------------------------------------------------

/** Terminal intent states — no further action needed. */
const TERMINAL_INTENT_STATES = new Set(["FILLED", "FAILED", "CANCELLED"]);

/** In-flight intent states — sent to exchange, awaiting completion. */
const IN_FLIGHT_INTENT_STATES = new Set(["PLACED", "PARTIALLY_FILLED"]);

/**
 * Classify a single intent for startup reconciliation.
 *
 * Rules:
 *   - PENDING intents → cancel (stale signal, unsafe to act on after restart)
 *   - PLACED/PARTIALLY_FILLED intents → monitor (exchange reconciliation loop
 *     will handle them, but startup should be aware)
 *   - FILLED/FAILED/CANCELLED → ok (terminal, no action needed)
 */
export function classifyIntent(intent: StartupIntent): IntentClassification {
  if (intent.state === "PENDING") {
    return {
      intentId: intent.intentId,
      id: intent.id,
      action: "cancel",
      reason: `stale PENDING ${intent.type} intent from before restart`,
    };
  }

  if (IN_FLIGHT_INTENT_STATES.has(intent.state)) {
    return {
      intentId: intent.intentId,
      id: intent.id,
      action: "monitor",
      reason: `${intent.state} ${intent.type} intent — exchange reconciliation will track`,
    };
  }

  return {
    intentId: intent.intentId,
    id: intent.id,
    action: "ok",
    reason: `terminal state ${intent.state}`,
  };
}

// ---------------------------------------------------------------------------
// Startup reconciliation
// ---------------------------------------------------------------------------

/**
 * Reconcile intent state on startup for a single run.
 *
 * Given the current intents and position state, produces a reconciliation
 * result describing what should be cancelled, monitored, and whether
 * it's safe to proceed with normal signal evaluation.
 *
 * Safety rule: it is safe to evaluate new signals ONLY when there are
 * no stale PENDING intents (all were cancelled) and the position state
 * is consistent. In-flight (PLACED) intents are OK — they're tracked
 * by the exchange reconciliation loop.
 *
 * Pure function: no I/O, no side effects, deterministic.
 */
export function reconcileStartupState(
  intents: StartupIntent[],
  position: PositionSnapshot | null,
): StartupReconciliationResult {
  const toCancel: IntentClassification[] = [];
  const toMonitor: IntentClassification[] = [];
  const terminal: IntentClassification[] = [];

  let pendingCount = 0;
  let placedCount = 0;
  let partiallyFilledCount = 0;
  let terminalCount = 0;

  for (const intent of intents) {
    const classification = classifyIntent(intent);

    switch (classification.action) {
      case "cancel":
        toCancel.push(classification);
        pendingCount++;
        break;
      case "monitor":
        toMonitor.push(classification);
        if (intent.state === "PLACED") placedCount++;
        if (intent.state === "PARTIALLY_FILLED") partiallyFilledCount++;
        break;
      case "ok":
        terminal.push(classification);
        terminalCount++;
        break;
    }
  }

  // Position-intent consistency: if open position exists and there are
  // stale PENDING ENTRY intents, they could cause duplicate entries.
  // Cancelling them (done above) prevents this.
  const hasOpenPosition = position !== null && position.status === "OPEN";
  const stalePendingEntries = toCancel.filter(
    (c) => intents.find((i) => i.id === c.id)?.type === "ENTRY",
  );

  // Safe to evaluate when no stale pending intents remain
  // (they will be cancelled by the caller before evaluation starts)
  const safeToEvaluate = true; // Always safe after cancellation is applied

  const parts: string[] = [];
  if (pendingCount > 0) {
    parts.push(`${pendingCount} stale PENDING → cancel`);
  }
  if (placedCount > 0 || partiallyFilledCount > 0) {
    parts.push(`${placedCount + partiallyFilledCount} in-flight → monitor`);
  }
  if (hasOpenPosition && stalePendingEntries.length > 0) {
    parts.push(`${stalePendingEntries.length} stale ENTRY intents with open position → prevented duplicate`);
  }
  if (parts.length === 0) {
    parts.push("clean startup — no reconciliation needed");
  }

  return {
    toCancel,
    toMonitor,
    terminal,
    safeToEvaluate,
    summary: parts.join("; "),
    counts: {
      pending: pendingCount,
      placed: placedCount,
      partiallyFilled: partiallyFilledCount,
      terminal: terminalCount,
      total: intents.length,
    },
  };
}

// ---------------------------------------------------------------------------
// Startup safety assessment
// ---------------------------------------------------------------------------

/**
 * Assess whether a startup state is internally consistent.
 *
 * Checks:
 *   1. No PENDING ENTRY intents when position is already OPEN
 *      (would cause duplicate entries)
 *   2. No PENDING EXIT intents when no position is OPEN
 *      (would try to exit a nonexistent position)
 *
 * Returns inconsistencies found. Empty array = consistent.
 *
 * Note: this checks BEFORE cancellation. The caller should cancel
 * stale intents first, then this should return no inconsistencies.
 */
export function detectStartupInconsistencies(
  intents: StartupIntent[],
  position: PositionSnapshot | null,
): string[] {
  const issues: string[] = [];
  const hasOpenPosition = position !== null && position.status === "OPEN";

  const pendingEntries = intents.filter(
    (i) => i.state === "PENDING" && i.type === "ENTRY",
  );
  const pendingExits = intents.filter(
    (i) => i.state === "PENDING" && i.type === "EXIT",
  );

  if (hasOpenPosition && pendingEntries.length > 0) {
    issues.push(
      `${pendingEntries.length} PENDING ENTRY intent(s) with open position — risk of duplicate entry`,
    );
  }

  if (!hasOpenPosition && pendingExits.length > 0) {
    issues.push(
      `${pendingExits.length} PENDING EXIT intent(s) with no open position — would exit nonexistent position`,
    );
  }

  return issues;
}
